#source 'http://2dfire.net:ios/cocoapods-spec'
#source 'https://github.com/fengxing1/mySpec'
use_frameworks!

platform :ios, '8.0'

target 'SMLagMonitor_Example' do
  pod 'SMLagMonitor', :path => '../'

  target 'SMLagMonitor_Tests' do
    inherit! :search_paths

    
  end
end
